# Export Processed Data

This notebook exports the cleaned and enriched dataset for use in Power BI and future analysis.

In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("../data/retail_ecommerce_talent_pool_clean.csv")

In [3]:
df["total_skills"] = (
    df["excel_skill"] +
    df["sql_skill"] +
    df["python_skill"] +
    df["power_bi_skill"] +
    df["looker_studio_skill"] +
    df["database_skill"] +
    df["tableau_skill"]
)

In [4]:
df["skill_level"] = pd.cut(
    df["total_skills"],
    bins=[-1, 2, 5, 7],
    labels=["Beginner", "Intermediate", "Advanced"]
)

In [5]:
df[["candidate_id", "total_skills", "skill_level"]].head()

   candidate_id  total_skills   skill_level
0             1             2      Beginner
1             2             4  Intermediate
2             3             5  Intermediate
3             4             2      Beginner
4             5             7      Advanced

In [7]:
df.to_csv(
    "../data/retail_ecommerce_talent_pool_processed.csv",
    index=False
)

In [8]:
processed_df = pd.read_csv(
    "../data/retail_ecommerce_talent_pool_processed.csv"
)

processed_df.head()

,candidate_id,city,fresh_graduate_status,skills,excel_skill,sql_skill,python_skill,power_bi_skill,looker_studio_skill,database_skill,...,other_skills,candidate_goals,platform_source,province,for_job,upskills,networking,switch_career,total_skills,skill_level
0,1,Jawa Tengah,Ya,"Python, Tableau",0,0,1,0,0,0,...,NaN,"Cari Kerja, Upskill, Networking",LinkedIn,Jawa Tengah,1,1,1,0,2,Beginner
1,2,Padang,Ya,"Excel, SQL, Python, Power BI",1,1,1,1,0,0,...,NaN,"Cari Kerja, Upskill, Networking, Switch Career",LinkedIn,Sumatera Barat,1,1,1,1,4,Intermediate
2,3,Surabaya,Ya,"Excel, SQL, Python, Power BI, Databases",1,1,1,1,0,1,...,NaN,"Cari Kerja, Upskill, Networking",Teman,Jawa Timur,1,1,1,0,5,Intermediate
3,4,Bandung,Ya,"Python, Power BI",0,0,1,1,0,0,...,NaN,Upskill,LinkedIn,Jawa Barat,0,1,0,0,2,Beginner
4,5,Yogyakarta,Tidak,"Excel, SQL, Python, Power BI, Looker Studio, D...",1,1,1,1,1,1,...,NaN,"Upskill, Networking, Switch Career",Teman,DI Yogyakarta,0,1,1,1,7,Advanced